apiVersion: v2
appVersion: "1.0"
description: A Helm chart for wa-proto-frontend App
name: wa-proto-frontend
home: https://github.com/hmcts/wa-proto-frontend
version: 0.0.11
maintainers: 
  - name: HMCTS WA team
