nodejs:
  environment:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment: 
    REDIS_URL: "redis://${SERVICE_NAME}-redis-master:6379"
  keyVaults:
    wa:
      secrets:
        - AppInsightsInstrumentationKey
redis:
  enabled: true
