nodejs:
  applicationPort: 3001
  image: 'hmctspublic.azurecr.io/wa/proto-frontend:latest'
  ingressHost: wa-proto-frontend.{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: wa
  environment: 
    REDIS_STORE: "true"
  keyVaults:
    wa:
      secrets:
        - AppInsightsInstrumentationKey
        - wa-redis-access-key
        - wa-redis-connection-string
redis:
  enabled: false
  cluster:
    enabled: false
    slaveCount: 0
  usePassword: false
  master:
    persistence:
      enabled: false
