apiVersion: v2
appVersion: "1.0"
description: A Helm chart for ia-wa-proto-frontend App
name: ia-wa-proto-frontend
home: https://github.com/hmcts/ia-wa-proto-frontend
version: 0.0.10
dependencies:
  - name: nodejs
    version: 2.0.1
    repository: '@hmctspublic'

